// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoIntegradorS6G7.Models;

#nullable disable

namespace ProyectoIntegradorS6G7.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260209042350_PermitirNulosEnPagos")]
    partial class PermitirNulosEnPagos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProyectoIntegradorS6G7.Models.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("contactoPrincipal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("razonSocial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ruc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("saldoPendiente")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ProyectoIntegradorS6G7.Models.Credito", b =>
                {
                    b.Property<string>("idObligacion")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("cuotas")
                        .HasColumnType("int");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("fechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("montoTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("nivelRiesgoIA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("recomendacionIA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("rucCliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("tasaInteres")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("idObligacion");

                    b.ToTable("Creditos");
                });

            modelBuilder.Entity("ProyectoIntegradorS6G7.Models.Pago", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("CreditoidObligacion")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("comprobanteRuta")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("fechaPago")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("firmaBase64")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("idObligacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("metodoPago")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("montoPagado")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("numeroCuota")
                        .HasColumnType("int");

                    b.Property<string>("observaciones")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("reciboNumero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("registradoPor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("CreditoidObligacion");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("ProyectoIntegradorS6G7.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("rucAsociado")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProyectoIntegradorS6G7.Models.Pago", b =>
                {
                    b.HasOne("ProyectoIntegradorS6G7.Models.Credito", "Credito")
                        .WithMany()
                        .HasForeignKey("CreditoidObligacion");

                    b.Navigation("Credito");
                });
#pragma warning restore 612, 618
        }
    }
}
